name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-win:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: i686-pc-windows-msvc
            name: pbbot-rq-${{ github.ref_name }}-win-i686.exe
          - target: x86_64-pc-windows-msvc
            name: pbbot-rq-${{ github.ref_name }}-win-x86_64.exe

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/main.exe
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}

  release-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#          - target: i686-unknown-linux-musl
#            name: pbbot-rq-${{ github.ref_name }}-linux-i686
          - target: x86_64-unknown-linux-musl
            name: pbbot-rq-${{ github.ref_name }}-linux-x86_64

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: multilib
        run: sudo apt-get install -y musl-tools
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/main
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}

  release-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            name: pbbot-rq-${{ github.ref_name }}-darwin-x86_64
          - target: aarch64-apple-darwin
            name: pbbot-rq-${{ github.ref_name }}-darwin-aarch64

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/main
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}
